### PR TITLE
Update TextExtractor.java

### PR DESCRIPTION
**Pull request by yuanice**
alter ""," split question

### CODE REVIEW

**Comment by kilowu** [comment]
Hi, @yuanice Could you provide an *full* example addressing the issue

**Comment by yuanice** [comment]
> Hi, @yuanice Could you provide an _full_ example addressing the issue

find some other issues  while use  '\'  ,I'll fix it later

**Comment by yuanice** [comment]
> Hi, @yuanice Could you provide an _full_ example addressing the issue

**Comment by cornmonster** [comment]
> > Hi, @yuanice Could you provide an _full_ example addressing the issue
> > quoteStarted完全没有意义在这
> 
> 图片

Hi,

I have reviewed your commit. What you said does make sense, but line 272 "quoteStarted = false;" should be removed, right?

Thanks,
Jon

**Comment by yuanice** [comment]
> I have reviewed your commit. What you said does make sense, but line 272 "quoteStarted = false;" should be removed, right?

no,line 269 "!quoteStarted " should be removed, for example csv  context is : "a","b" ,They can't partition properly

**Comment by lyman** [comment]
Seems travis changed behavior due to security risk which caused CI failure. Merge first anyway and fix CI ASAP.

**Comment by kilowu** [comment]
> > I have reviewed your commit. What you said does make sense, but line 272 "quoteStarted = false;" should be removed, right?
> 
> no,line 269 "!quoteStarted " should be removed, for example csv context is : "a","b" ,They can't split properly.If you don't want to romve "!quoteStarted" ,only romve "!" It's ok

It's indeed a bug. Thank you @yuanice 

By the way, the TextExtractor is only an example for demo purpose. Please use built-in com.aliyun.odps.CsvStorageHandler if your files are CSV based format.

**Comment by yuanice** [comment]
> > > I have reviewed your commit. What you said does make sense, but line 272 "quoteStarted = false;" should be removed, right?
> > 
> > 
> > no,line 269 "!quoteStarted " should be removed, for example csv context is : "a","b" ,They can't split properly.If you don't want to romve "!quoteStarted" ,only romve "!" It's ok
> 
> It's indeed a bug. Thank you @yuanice
> 
> By the way, the TextExtractor is only an example for demo purpose. Please use built-in com.aliyun.odps.CsvStorageHandler if your files are CSV based format.

CsvStorageHandler There are problems，do not work correctly  when  files are CSV

**Comment by kilowu** [comment]
> CsvStorageHandler There are problems，do not work correctly when files are CSV

@yuanice Could you describe the problems in CsvStorageHandler? Thank you in advance.

**Comment by yuanice** [comment]
> > CsvStorageHandler There are problems，do not work correctly when files are CSV
> 
> @yuanice Could you open an issue and describe the problems in CsvStorageHandler? Thank you in advance.
 for example csv context is :
"a","b
b1"
It's going to split into two rows.

**Pull request merged**
